name: Greetings

on: 
  push: 
    branches:
      - main # Specify branches where the action should run on push (replace 'main' with your desired branch)
      - feature/* # Example for feature branches; you can adjust this as needed

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Message that will be displayed on users' first issue"
        pr-message: "Message that will be displayed on users' first pull request"
